<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-14T09:01:47Z" name="Facebook" finished-at="2021-05-14T09:02:57Z" duration-ms="70063">
    <groups>
    </groups>
    <test started-at="2021-05-14T09:01:47Z" name="Test" finished-at="2021-05-14T09:02:57Z" duration-ms="70063">
      <class name="pom.FlipkartTests">
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.FlipkartTests@d21a74c]" started-at="2021-05-14T09:01:47Z" name="before" finished-at="2021-05-14T09:01:52Z" duration-ms="5066" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f61371d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="flipkartValidInputTest()[pri:0, instance:pom.FlipkartTests@d21a74c]" started-at="2021-05-14T09:01:52Z" name="flipkartValidInputTest" finished-at="2021-05-14T09:01:54Z" duration-ms="2662" status="FAIL">
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element <div class="_4921Z t0pPfW" title="6 GB &amp; Above">...</div> is not clickable at point (143, 515). Other element would receive the click: <div class="_213eRC _2ssEMF">...</div>
  (Session info: chrome=90.0.4430.93)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-7KPE3BUK', ip: '192.168.174.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: C:\Users\saith\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:53224}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 311428a5105165f19491e3b9176b064c]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <div class="_4921Z t0pPfW" title="6 GB &amp; Above">...</div> is not clickable at point (143, 515). Other element would receive the click: <div class="_213eRC _2ssEMF">...</div>
  (Session info: chrome=90.0.4430.93)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-7KPE3BUK', ip: '192.168.174.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: C:\Users\saith\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:53224}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 311428a5105165f19491e3b9176b064c
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at pom.WebPage.select(WebPage.java:79)
at pom.FlipkartProductsPage.enterTheRamSize(FlipkartProductsPage.java:54)
at pom.FlipkartTests.flipkartValidInputTest(FlipkartTests.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flipkartValidInputTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.FlipkartTests@d21a74c]" started-at="2021-05-14T09:01:55Z" name="quit" finished-at="2021-05-14T09:01:55Z" duration-ms="683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- pom.FlipkartTests -->
      <class name="pom.FacebookTests">
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:03Z" name="before" finished-at="2021-05-14T09:02:06Z" duration-ms="2587" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f61371d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="invalidCreateNewAccount()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:06Z" name="invalidCreateNewAccount" finished-at="2021-05-14T09:02:33Z" duration-ms="26711" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [An error occurred. Please try again.] but found [Please choose a more secure password. It should be longer than 6 characters, unique to you and difficult for others to guess.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [An error occurred. Please try again.] but found [Please choose a more secure password. It should be longer than 6 characters, unique to you and difficult for others to guess.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pom.FacebookTests.invalidCreateNewAccount(FacebookTests.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCreateNewAccount -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:33Z" name="quit" finished-at="2021-05-14T09:02:34Z" duration-ms="678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:34Z" name="before" finished-at="2021-05-14T09:02:36Z" duration-ms="2522" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f61371d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="invalidForgotPasswordTest()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:36Z" name="invalidForgotPasswordTest" finished-at="2021-05-14T09:02:38Z" duration-ms="2329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidForgotPasswordTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:38Z" name="quit" finished-at="2021-05-14T09:02:39Z" duration-ms="701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:39Z" name="before" finished-at="2021-05-14T09:02:41Z" duration-ms="2378" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f61371d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="invalidLogInTest()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:41Z" name="invalidLogInTest" finished-at="2021-05-14T09:02:56Z" duration-ms="14291" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The password that you've entered is incorrect. Forgotten password?]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The password that you've entered is incorrect. Forgotten password?]
at pom.FacebookTests.invalidLogInTest(FacebookTests.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [The email address or mobile number you entered isn't connected to an account. Find your account and log in.] but found [The password that you've entered is incorrect. Forgotten password?]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pom.FacebookTests.invalidLogInTest(FacebookTests.java:44)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLogInTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.FacebookTests@2898ac89]" started-at="2021-05-14T09:02:56Z" name="quit" finished-at="2021-05-14T09:02:57Z" duration-ms="678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- pom.FacebookTests -->
      <class name="pom.HerokuTests">
        <test-method is-config="true" signature="before(org.testng.ITestContext)[pri:0, instance:pom.HerokuTests@6e509ffa]" started-at="2021-05-14T09:01:55Z" name="before" finished-at="2021-05-14T09:02:02Z" duration-ms="6507" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5f61371d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="addRemoveElementsTest()[pri:0, instance:pom.HerokuTests@6e509ffa]" started-at="2021-05-14T09:02:02Z" name="addRemoveElementsTest" finished-at="2021-05-14T09:02:03Z" duration-ms="883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addRemoveElementsTest -->
        <test-method is-config="true" signature="quit()[pri:0, instance:pom.HerokuTests@6e509ffa]" started-at="2021-05-14T09:02:03Z" name="quit" finished-at="2021-05-14T09:02:03Z" duration-ms="669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- pom.HerokuTests -->
    </test> <!-- Test -->
  </suite> <!-- Facebook -->
</testng-results>
